### ISSUE TITLE
A problem occurred starting process 'command './check_audio_files.pl''

### ISSUE THREAD

**Issue by Rudloff** [De7vID/klingon-assistant-android#42]
Hello,

I'm getting this error when trying to build v2018.11.20a:
```
Execution failed for task ':app:checkAudioFiles'.
> A problem occurred starting process 'command './check_audio_files.pl''
```

This file does not exist. Am I missing something?

**Comment by De7vID** [comment]
That script is here:
https://github.com/De7vID/klingon-assistant/blob/master/scripts/check_audio_files.pl

You won't ever need to run the `checkAudioFiles` target unless you're syncing the TTS to the app's database (i.e., the TTS has to be updated if any new sounds are needed because of a data change). In that case, you'll need to have both the [klingon-assistant-android](https://github.com/De7vID/klingon-assistant-android) and the [klingon-assistant-tts-android](https://github.com/De7vID/klingon-assistant-tts-android) checked out under the same parent directory. The [klingon-assistant](https://github.com/De7vID/klingon-assistant) project is set up to do that.

**Comment by Rudloff** [comment]
> You won't ever need to run the checkAudioFiles target

Well, I am running `assembleRelease` and `checkAudioFiles` is called automatically.

**Comment by De7vID** [comment]
This should be fixed in the new release:
https://github.com/De7vID/klingon-assistant-android/releases/tag/v2019.07.23a
